#!/bin/bash
token=""

# Enable Cloudflare Tunnel default
if [[ -z "$(opkg list-installed cloudflared)" ]]; then
    echo "cloudflared 未安装"
    exit 1
fi

if [[ -z "$(uci get cloudflared.config.token)" ]]; then
    uci set cloudflared.config.enabled=1
    uci set cloudflared.config.token=$token
    uci set cloudflared.config.region='us'
    uci commit
fi