#!/bin/bash
# 开启NAT6

# 关闭wan接口前缀申请
# uci set network.$INTERFACE.reqprefix=no
# uci set network.wan6.delegate='0'
# 开启IPv6 NAT规则（该规则由default设置，处于未启用状态名称为nat6）
nat_status=$(
    uci show firewall | grep -Eo 'firewall.@nat\[[0-9]*\]' | sort -u | \
    while read -r line; do
        if [[ "$(uci get ${line}.src)" == "wan" && "$(uci get ${line}.family)"="ipv6" && "$(uci get ${line}.target)" = "MASQUERADE" ]]; then
            uci set ${line}.enabled=1
            echo "$line"
            break
        fi
    done
)

if [[ -z "$nat_status" ]]; then
    natid=$(uci add firewall nat)
    uci set firewall.$natid.name=NAT6
    uci set firewall.$natid.family=ipv6
    uci set firewall.$natid.src=wan
    uci set firewall.$natid.target=MASQUERADE
    uci set firewall.$natid.proto=all
    uci set firewall.$natid.enabled=1
fi
uci commit


echo -e "提示：如果安装了mwan3(链路聚合与负载均衡)必须到mwan3配置中添加并启用对应接口否则将无法使用IPv6
不使用公网请关闭对应接口的\"请求IPv6前缀\"选项或\"委托IPv6前缀\"开关"