#!/bin/bash
if [[ -z "$(opkg list-installed qbittorrent-enhanced-edition)" ]]; then
  echo "qbittorrent-enhanced-edition 未安装"
  exit 1
fi

if [[ "$(uci get qbittorrent.config.download_dir)" == "/mnt/download" ]]; then
  mkdir -p /mnt/mmcblk0p27/qbittorrent
  uci set qbittorrent.config.download_dir='/mnt/mmcblk0p27/qbittorrent'
  uci commit
fi