#!/bin/bash
if [[ -z "$(uci get wan_mac)" ]]; then
  uci set wan_mac.config.enabled=1
  uci set wan_mac.config.prefix='7C10C9'
  uci set wan_mac.config.macaddr='7C:10:C9:42:B1:E6'
  uci commit wan_mac
fi
