#!/bin/bash
uci set wireless.default_radio0.ssid='JDC_AX1800PRO'
#uci set wireless.default_radio0.encryption='none'
uci set wireless.default_radio0.encryption='sae-mixed'
if [[ -z "$(uci get wireless.default_radis0.ifname)" ]]; then
    uci set wireless.default_radio0.ifname='5G'
fi

uci set wireless.default_radio1.ssid='JDC_AX1800PRO'
#uci set wireless.default_radio1.encryption='none'
uci set wireless.default_radio1.encryption='sae-mixed'
if [[ -z "$(uci get wireless.default_radis1.ifname)" ]]; then
    uci set wireless.default_radio1.ifname='2.4G'
fi

uci commit
